### ISSUE TITLE
A line per person - Who is in Melbourne

### ISSUE THREAD

**Issue by adamcogan** [SSWConsulting/SSW.SophieBot#1]
For Question: Who is in Melbourne

Change from
   There are 12 people in Melbourne:
   Anthony Nguyen | William Liebenberg | Chris Clement | Harry Phan 
To
   There are 12 people in Melbourne:
   1. Anthony Nguyen 
   2. William Liebenberg
   3. Chris Clement
   4. Harry Phan

PS: If only 1 result then show a card

![image](https://user-images.githubusercontent.com/1222712/129319137-65749fd0-5adf-4244-9550-b46b3f86b6b9.png)

**Comment by PatrickZhao1989** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [1. Type "Who works in Melbourne?"](https://trello.com/c/cAvxG6ro/6-1-type-who-works-in-melbourne)
