### ISSUE TITLE
2. Type "Who knows Azure?"

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#14]
![image](https://user-images.githubusercontent.com/37203901/131076236-2b8234d1-b07c-431f-aa96-54d38236275e.png)
Figure: Who knows Azure flow

**Comment by jimmidier** [comment]
- [ ] Support query "I need help with Azure"

**Comment by AttackOnMorty** [comment]
> * [ ]  Support query "I need help with Azure"

Duplicated. Refer to https://github.com/SSWConsulting/SSW.SophieBot/issues/298
