### ISSUE TITLE
Query - who is working on sugarlearning

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#143]
To Myself,

cc @AttackOnMorty @PatrickZhao1989 @pierssinclairssw @adamcogan 

1. Bug - see below:
2. Formatting - Remove "development" on the list card heading

![image](https://user-images.githubusercontent.com/16027480/137691464-51200174-71c5-48e9-804a-b42f4f976084.png)
**Figure: Bug - Incorrect recognition**

![image](https://user-images.githubusercontent.com/16027480/137692121-c63d49bd-3902-409e-8913-bb8496a08fb2.png)
**Figure: Formatting - Original response card with "development" in the heading**

**Comment by AttackOnMorty** [comment]
- [ ] Remove column `name` label
- [ ] Center the column header and body
- [ ] Change column header “Booking Status” to “Booking”

**Comment by AttackOnMorty** [comment]
- [ ] `More Project Info` button redirects to the specific project.
- [ ] Card style - For names, make color white and add underline. Also remove the separators between rows.

**Comment by AttackOnMorty** [comment]
- [ ] Use dynamic icon for More project info button
