### ISSUE TITLE
3. Type "I need to talk to a DevOps expert in Melbourne"

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#15]
![image](https://user-images.githubusercontent.com/16027480/130719504-eed5930a-b620-4030-8720-e04c65b4a539.png)

![image](https://user-images.githubusercontent.com/16027480/131273629-89bb667b-5ebe-4466-8c46-ff7cb2aa1b43.png)

**Comment by jimmidier** [comment]
![image](https://user-images.githubusercontent.com/16027480/130564184-3b97771f-46e5-494e-87f4-146c22a26703.png)
