### ISSUE TITLE
13. Type "Who is free next Friday in Melbourne with Angular skills?"

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#20]
![image](https://user-images.githubusercontent.com/16027480/131272693-9fc80cc2-6ebf-4f11-b307-4f247814d864.png)

**Comment by jimmidier** [comment]
- [ ] Refine response message when result employees are single or multiple

**Comment by AttackOnMorty** [comment]
- [ ] Can we make the date query string optional?
![image](https://user-images.githubusercontent.com/37203901/132639714-2c53ed6e-2461-40ee-be6e-c2d9aac1abb2.png)
**Figure: Get error when missing date**

**Comment by jimmidier** [comment]
- [ ] change all person queries response to a consistent look. i.e. list card with photo, name, next client

**Comment by jimmidier** [comment]
- [ ] Remove text message (Anthony, Patrick and Tom are not on client work), just show the card
- [ ] Format "Next Client" to same as who-is-free-next-Friday query

**Comment by jimmidier** [comment]
> > * [ ]   Change Availability column from
> > 
> > ```
> > Availability
> > Only free for 1 day
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```
> > Availability next 4 weeks
> > 27/28 days
> > ```
> 
> We're currently unable to retrieve correct available days because:
> 
> * People API only syncs appointments for next month, so when the date range exceeds one month from now, it leeds to incorrect calculation result
> * People API doesn't include a type field, so it's difficult to decide whether it is a leave appointment  

> People API only syncs appointments for next month, so when the date range exceeds one month from now, it leeds to incorrect calculation result  

Fixed.

> People API doesn't include a type field, so it's difficult to decide whether it is a leave appointment

Fixed.

**Comment by AttackOnMorty** [comment]
- [ ] Make it three columns name, availability for `this 4 weeks` and `next 4 weeks`

**Comment by AttackOnMorty** [comment]
> * [ ]  Make it three columns name, availability for `this 4 weeks` and `next 4 weeks`

As per conversion with @pierssinclairssw and @adamcogan, remove this todo. Will do the following change:
- [ ] Change date text
From
`Friday 26 November`
To
`Available: Friday 26 November`
![image](https://user-images.githubusercontent.com/37203901/142375078-44532436-12da-4b1e-97b6-a0e61bdd75bd.png)
**Figure: Bot response**

**Comment by jimmidier** [comment]
- [ ] Support query - "Who is free today with React skills?"
