### ISSUE TITLE
12. Type "Who is on client work next Friday?"

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#21]
![image](https://user-images.githubusercontent.com/37203901/131769280-e2a60b93-a74f-4eee-a642-c9c6495ae71d.png)
**Figure: Who is on client work next Friday flow**

**Comment by AttackOnMorty** [comment]
![image](https://user-images.githubusercontent.com/37203901/132528596-815c146a-ed1f-4c5a-bff2-8a748bde847a.png)

**Comment by AttackOnMorty** [comment]
- [ ] Bold the Date text response
- [ ] Change the second text response to "narrow your search..."

**Comment by AttackOnMorty** [comment]
- [ ] Change the response to
```
On Friday 24 September we have 
Kosta, Andreas, Matt and 17 others are on client work.
Narrow your search...
```

**Comment by jimmidier** [comment]
- [ ] test "More Booking Info" button
