### ISSUE TITLE
Query - What is Uly's skills

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#217]
Auto name correction (Refer to #140 and #141)

**Comment by AttackOnMorty** [comment]
- [ ] Fix query `what is ulys skills`
![image](https://user-images.githubusercontent.com/37203901/141708638-67af87b4-6dec-443c-ab28-ae9f712b72c5.png)
**Figure: Should answer with Uly's skills**

**Comment by AttackOnMorty** [comment]
Opened a new issue for the bug on this. Refer to #338
