### ISSUE TITLE
14. Type "Who is working for SSW Today?"

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#22]
![image](https://user-images.githubusercontent.com/37203901/132450145-fc1fd243-c2db-48f1-8e37-99f2c7f2bdc9.png)

**Comment by AttackOnMorty** [comment]
![image](https://user-images.githubusercontent.com/37203901/132528838-244102cb-e5c3-4ec8-9b1e-e0be6c21ad33.png)

**Comment by jimmidier** [comment]
- [ ] Consider extracting client entity from the query, and give response for the specific client

**Comment by AttackOnMorty** [comment]
> * [ ]  Consider extracting client entity from the query, and give response for the specific client

We can't simply extract SSW as the client entity. `Who is working for SSW Today?` and `Who is working for SSW?` are actually different queries.

- `Who is working for SSW Today?` is similar to `who is on client work`, `who is free`. They are all availability check queries. Query strings are `booked`, `location` and `fromDate`.
- `Who is working for SSW` is a client query. It has different query strings and logic. Query strings are `client` and `location`. It doesn't support `fromDate`.

Since `Who is working for SSW Today?` already contains 4 queries. Created [another issue](https://github.com/SSWConsulting/SSW.SophieBot/issues/74) for `Who is working for SSW`. Ping me if I didn't make myself clear.

**Comment by AttackOnMorty** [comment]
- [ ] Bold the date text response
- [ ] Change the second text response to "narrow your search..."
- [ ] Make the card fixed width to put three buttons in one row
- [ ] Change list title to "Internal work- All/Remote/Sydney" in the people list card
- [ ] Change "Subject" column header to "Appointment"
