### ISSUE TITLE
15. Type "Who is in the Sydney office right now?"

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#23]
![image](https://user-images.githubusercontent.com/16027480/133747953-c4c524f3-e719-4b7b-86dd-29ad8950e6eb.png)

**Comment by jimmidier** [comment]
- [ ] Show profile card when quired location only has 1 people currently.

**Comment by jimmidier** [comment]
- [ ] Change column header in list card - "Billed Days" -> "Billed (arrow down)"
- [ ] Change "0 Day" to "-" in list card
- [ ] Refine Last Seen data - use full words e.g. "d" -> "day/days"
- [ ] Replace "choose an item" with "narrow your search..."

**Comment by jimmidier** [comment]
- [ ] make the legend single line
- [ ] Change legend shape from circle to square (need confirm)

**Comment by AttackOnMorty** [comment]
- [ ] Change the legend shape to the circle
- [ ] Capitalize location

**Comment by AttackOnMorty** [comment]
- [ ] Booking status logic should not be calculated by the current date
- [ ] Add date info to the list title

**Comment by AttackOnMorty** [comment]
- [ ] Data is not correct. It should return 3 people when ask `Who is in the Sydney office right now?`

![image](https://user-images.githubusercontent.com/37203901/139609704-2a91c999-f65b-47e1-98e5-5112fabbd837.png)

![image](https://user-images.githubusercontent.com/37203901/139609713-a4161089-fce8-43d4-8b55-9e7306c16926.png)

**Comment by AttackOnMorty** [comment]
- [ ] Melbourne and Brisbane not working. Also check other locations.
![image](https://user-images.githubusercontent.com/37203901/139632392-c09bd7be-4bae-4ee6-87d1-c07ac57023aa.png)

**Comment by jimmidier** [comment]
- [ ] Remove @site list entity and getting sites from crm instead
