### ISSUE TITLE
Query shows next 10 instead of pages

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#232]
- [x] Change who works in Melbourne to display pages instead of next 10.
- [x] Check if any other queries need to be changed as well.

![image](https://user-images.githubusercontent.com/37203901/140458214-f8878de8-7cbe-44b4-a6f6-a329c2ad5b80.png)
**Figure: Bad example – The Who works in Melbourne query shows next 10…**

**Comment by jimmidier** [comment]
Done in #234
