### ISSUE TITLE
16. Report a bug - Type "Hey this is broken"

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#24]
![image](https://user-images.githubusercontent.com/16027480/131307912-7df30311-2615-4186-9932-fc779181b672.png)

**Comment by jimmidier** [comment]
- [ ] Refine response message

from:
Please send an email with questions and screenshots to my friend williamliebenberg@ssw.com.au. He loves squashing bugs.

to:
Please send an email with questions and screenshots to sswsophiebotdevs@ssw.com. We love squashing bugs.
www.sswsophie.com

**Comment by jimmidier** [comment]
- [ ] Change response to:
No worries, please send us an email with your feedback and screenshots to  [SSWSophieBotDevs@ssw.com.au](mailto:SSWSophieBotDevs@ssw.com.au)
