### ISSUE TITLE
Query - Who do I report a timepro bug to?

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#263]
Implement the below:
 
Q: Who do I report a timepro bug to?
A: Sorry I could not answer that.
See all queries www.sswsophie.com/SophieBot 
Try SSW Intranet https://sswcom.sharepoint.com

**Comment by jimmidier** [comment]
- [ ] Change the second line to "See sample queries"
- [ ] After "See sample queries", add a new line and say "you can also search the ssw intranet {url}"
- [ ] Add an emoji to the end of "sorry I cound't answer that"
