### ISSUE TITLE
🐛 Sophie not responding properly to availability question.

### ISSUE THREAD

**Issue by theixdev** [SSWConsulting/SSW.SophieBot#294]
CC: @jimmidier @adamcogan 

Please see below image of Sophie response to query about availability of employees with skills on a particular day.

![image](https://user-images.githubusercontent.com/77970786/142408165-bb5efa6a-a567-4bda-b7ef-abb24316f1c8.png)

**Comment by AttackOnMorty** [comment]
Duplicated. Refer to https://github.com/SSWConsulting/SSW.SophieBot/issues/20#issuecomment-973854791
