### ISSUE TITLE
🐛 SophieBot does not recognize Kiki/Kaique

### ISSUE THREAD

**Issue by kikibianc** [SSWConsulting/SSW.SophieBot#295]
Cc: @jimmidier @AttackOnMorty 

To @jimmidier 
  
### Pain

SophieBot can't find me :( 

When asking:
1. Who is Kaique?
2. Who is Kaique Biancatti?
3. Who is Kiki?

It only finds me when asking office questions, like "Who is in Sydney?"

### Tasks

- [ ] Fix query "Who is Kaique?" and "Who is Kaique Biancatti?"
- [ ] Make PeopleAPI supports searching by the nickname. 
Refer to https://dev.azure.com/ssw/SSW.SophieBot/_workitems/edit/65657

### Screenshots

![image](https://user-images.githubusercontent.com/5884297/142514731-acaa52ff-6059-461e-8cf8-7d99068b4633.png)
**Figure: Bot doesn't show my card**

Thanks!

**Comment by jernejk** [comment]
I know, it's terrible. 😰
Also, I made a duplicate by mistake: #320
