### ISSUE TITLE
Type "Goodbye"

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#30]
![image](https://user-images.githubusercontent.com/37203901/130896226-e744dd08-ccff-48c1-a29e-6a3af7a7cc40.png)
**Figure: [Goodbye Dialogflow](https://dialogflow.cloud.google.com/#/agent/ssw-bots/editIntent/2a7c066d-f5c3-4b94-b02b-0571bd708bf0/)**

**Comment by AttackOnMorty** [comment]
Some other phrases will lead to Goodbye intent.
- [ ] Use exact match for Goodbye phrases

**Comment by jimmidier** [comment]
- [ ] Refine response message

from:
Please send an email with questions and screenshots to my friend williamliebenberg@ssw.com.au. He loves squashing bugs.

to:
Please send an email with questions and screenshots to sswsophiebotdevs@ssw.com. We love squashing bugs. 
www.sswsophie.com

**Comment by AttackOnMorty** [comment]
- [ ] Change the response
      From:
      Goodbye. Please give us feedback at SSWSophieBot@ssw.com.au
      To: 
      Thanks for using SophieBot. Please give us feedback at SSWSophieBotDevs@ssw.com.au
