### ISSUE TITLE
♻️ LUIS - Hey Sophie

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#300]
Cc: @jimmidier @landonmaxwell

  
### Pain

From @landonmaxwell's feedback,
> • Who is Sophiebot? (shows “on client work” instead of info about SophieBot) 
• What is SophieBot? 
• Where do you get your data?

We need to support a wider range of greeting responses.

### Tasks

- [ ] Add more phrases to `Hey Sophie` query
  - Who is Sophiebot? (this is also a  LUIS problem)
  - What is SophieBot?
  - Where do you get your data?

### Screenshots

![image](https://user-images.githubusercontent.com/37203901/142793042-599ae0b7-9ee1-499b-a03d-64c20b0efd21.png)
**Figure: Missing or incorrect queries on SophieBot**

Thanks!

**Comment by jimmidier** [comment]
Done by adding more phrases for this intent.

![image](https://user-images.githubusercontent.com/16027480/151366957-947190cf-0537-4922-9e75-69a1d3298f7c.png)
**Figure: Support more phrases for greeting intent**
