### ISSUE TITLE
✨Query - Who is Sydney office manager

### ISSUE THREAD

**Issue by zl24622** [SSWConsulting/SSW.SophieBot#302]
As a user, I may need to find right people to do some tasks. The Bots can check people's job title.
E.g.
Q: Who is network administrators?
A: Kiki

Who is SSW accountant?
A: Nick

Who is Sydney manager?
A: Adam | Uly

**Comment by jimmidier** [comment]
Hi @zl24622 

Thanks for your feedback.
Moved to #323
