### ISSUE TITLE
🐛 Images blocked in China

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#306]
Cc: @AttackOnMorty 

  
### Pain

Images seem to be blocked in China

### Tasks

- [ ] Investigate on the real cause

### Screenshots

<img width="726" alt="8f82a8ea5ff06f0fe22fd3c82b0a59c" src="https://user-images.githubusercontent.com/16027480/142589290-11e3b30c-98c1-457b-9017-a345045c8b66.png">
<img width="504" alt="766f9d5d1ee137bb67abfb981272805" src="https://user-images.githubusercontent.com/16027480/142589298-f6078515-8113-40b4-a3a8-b154b95d0aa7.png">

Thanks!

**Comment by AttackOnMorty** [comment]
Moved to #253
