### ISSUE TITLE
🐛 Failed recognition on "ef core" skill entity

### ISSUE THREAD

**Issue by jernejk** [SSWConsulting/SSW.SophieBot#319]
Cc:

Hi team,

### Describe the Bug
Nobody is calling EF Core as `.NET EF Core`, it's called `EF Core` (or `Entity Framework` for legacy .NET Framework version).
I thought the skills feature was broken but it turns out the skill name to be incorrect.

`.NET EF Core` does not exist.

### To Reproduce
1. Type `Who knows ef core?`
2. It's an unknown feature

### Expected Behavior

EF Core is the correct skill name.

### Tasks
- [ ] Improve LUIS model

### Environment
 - Device: Laptop
 - OS: Windows 11

### Screenshots
![image](https://user-images.githubusercontent.com/5943653/142960499-61acc17f-200b-4ac1-a57b-77df7c8e8035.png)

Thanks!

**Comment by jimmidier** [comment]
Hi @jernejk 

Thanks for your feedback

* The skill info is retrieved from CRM system and the name cannot be changed from SophieBot. 
* The issue in the screenshot above is due to failed LUIS recognition on the word "ef core". I'll change the ttitle and the task to reflect the real problem here.

**Comment by jimmidier** [comment]
This bug has closed by a temporary fix. Further fix will be tracked in #342
