### ISSUE TITLE
✨ When is Adam's birthday?

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#321]
Cc: @UlyssesMaclaren @jimmidier @pierssinclairssw 

To myself,
  
### Pain

Feedback from @UlyssesMaclaren,
> When is Adam's birthday?

People might want to know someone's birthday and give them some surprise.

### Tasks

- [x] Add birthday data field data to PeopleAPI
- [x] Implement the query

Thanks!

**Comment by ravidhaduk** [comment]
As per the email from Chris C and conversation with Ulysses, we have to put authentication in this query, so only SSW employees will have access to this information. And we have to remove the birth year from the birthdate to limit the exposure.

- [ ] Add authentication.
- [ ] Format birthdate.

**Comment by ravidhaduk** [comment]
Done - Authentication has been added and removed birth year from the birth date.

Not adding any screenshots for privacy reasons.
