### ISSUE TITLE
✨ Query - What's Jean's next booking?

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#322]
Cc: @JeanThirion @AttackOnMorty @pierssinclairssw 

  
### Pain

From @JeanThirion's feedback,
> "What's my next meeting"

We need to support queries relating a specific booking

### Tasks

- [ ] Query - "What's Jean's next booking?"

Thanks!

**Comment by AttackOnMorty** [comment]
Related to #224

**Comment by AttackOnMorty** [comment]
Duplicated. Refer to #224
