### ISSUE TITLE
♻️ Change logo for SSW People button to use the four squares version

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#325]
Cc: @jaydenalchin @AttackOnMorty 

  
### Pain

From @jaydenalchin's feedback,
> I would use the 4 squares for the logo on the "View in People" button instead of what looks like a squished down SSW logo  

Change the icon for the "View in People" button on profile card

### Tasks

- [ ] Use this one instead [https://www.ssw.com.au/ssw/include/pigeon/img/favicon-32x32.png](https://www.ssw.com.au/ssw/include/pigeon/img/favicon-32x32.png)

### Screenshots

![image](https://user-images.githubusercontent.com/16027480/142967774-19029dbb-e3df-47c9-8fd8-d6f678c21d8a.png)
**Figure: Profile card with "View in People" button**

Thanks!

**Comment by AttackOnMorty** [comment]
Moved this into a task of #332
