### ISSUE TITLE
♻️ Change the "V" in more button in profile card to a more solid one

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#326]
Cc: @AttackOnMorty @pierssinclairssw 

  
### Pain

As per the user feedback, we should change the "V" symbol on profile card into a more solid one. See screenshot below

### Suggested Solution

Use icon.

### Tasks

- [ ] Replace "V" with an icon

### Screenshots

![image](https://user-images.githubusercontent.com/16027480/142968435-17cdeb2b-84cb-4bbd-8c43-974d52545709.png)
**Figure: "More" button with a character "V" on profile card**

Thanks!

**Comment by AttackOnMorty** [comment]
Moved this into a task in #332
