### ISSUE TITLE
Add handling for all unknown queries

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#33]

**Comment by AttackOnMorty** [comment]
- [ ]  For those greetings, they shouldn't be identified as unknown intents. We could have a simple greeting back.
![image](https://user-images.githubusercontent.com/37203901/132638980-3f6f6f82-64ba-48a1-b898-fb16f56983db.png)
**Figure: Unknown intent pharses**

**Comment by jimmidier** [comment]
- [ ] Change response from:
    Sorry I didn’t understand your phrase. Can you please try again?
To:
    Sorry I didn’t understand. Can you please try again?
