### ISSUE TITLE
✨  Project queries for people

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#372]
Cc: @PatrickZhao1989 @jimmidier 

To myself,
  
### Pain

Feedback from @PatrickZhao1989 
> Can we support the queries below?
a. “What is Patrick working on?”
b. “What are Patrick’s projects?”
c. The profile card should have a 4th button – “View Projects”
Users want to know someone's project info.

### Tasks

- [ ] Implement queries below:
- “What is Patrick doing?”
- “What is Patrick working on?”
- “What are Patrick’s projects?”
- [ ] Add “View Projects” button on the profile card

### Screenshots

![image](https://user-images.githubusercontent.com/16027480/148322986-6e15c974-5d5c-4c7b-bd5a-73ab04301bcf.png)
**Figure: Bot can't answer project related queries**

Thanks!

**Comment by jimmidier** [comment]
Done by adding a new intent and a new dialog for project queries.

![image](https://user-images.githubusercontent.com/16027480/151367418-51c3ddc8-1ba5-46f7-9ce5-3873f042968b.png)
**Figure: Various ways to query employee projects**
