### ISSUE TITLE
✨  Add multitenancy to PeopleAPI

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#379]
Cc: @DavidAbraham082 @PatrickZhao1989 @pierssinclairssw @adamcogan 

Hi @jimmidier 
  
### Pain

Users/Organizations outside of SSW are going to use our Bot. We need the multitenancy feature to differentiate them.

### Tasks

- [ ] ~Add new fields (e.g. Email, Picing Tier, Sign up time) in Table Storage to support multitenancy~

### More Information

As @jimmidier noted:
> There is no really database schema change needed as Table Storage is NoSQL. New fields will be created by code

### Screenshots

![image](https://user-images.githubusercontent.com/37203901/146511095-f644519d-bda4-4131-8d42-d42dbd84bac6.png)
Figure: Current Table Storage schema

Thanks!

**Comment by jimmidier** [comment]
Canceled as we decided not to implement multitenancy
