### ISSUE TITLE
✨ Add public API docs for PeopleAPI query endpoints

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#380]
Cc: @DavidAbraham082 @PatrickZhao1989 @pierssinclairssw @adamcogan 

Hi @jimmidier 
  
### Pain

We need a public PeopleAPI doc for external users to reference.

### Tasks

- [ ] ~Investigate what API docs tools should we use, e.g. Swagger~
- [ ] ~Implement~

Thanks!

**Comment by jimmidier** [comment]
Canceled as we decided not to implement multitenancy
