### ISSUE TITLE
📝 Update Architecture Diagram

### ISSUE THREAD

**Issue by adamcogan** [SSWConsulting/SSW.SophieBot#390]
Cc: @jimmidier  @PatrickZhao1989  @pierssinclairssw 

Hi @DavidAbraham082 

Update the Architecture Diagram https://github.com/SSWConsulting/SSW.SophieBot/wiki
Use draw.io

1. To reflect the Custom Dynamics365 app (aka a PowerApps Solution approach) 
2. Indicate somewhere we do not store any of the customers data (that would happen in a SaaS service)
3. Put the data at the top as per https://www.ssw.com.au/rules/architecture-diagram
4. Check the draw.io (now Diagraws.net) file is accessable by the team
 
-a
www.adamcogan.com

**Comment by DavidAbraham082** [comment]
> Update the Architecture Diagram https://github.com/SSWConsulting/SSW.SophieBot/wiki

**Done**

> Indicate somewhere we do not store any of the customers data

**Done - note at bottom of arch diagram**

> Check the .drawio file is accessable by the team

**Done - https://github.com/SSWConsulting/SSW.SophieBot/blob/main/_docs/architecture.drawio**

**Comment by jimmidier** [comment]
- [ ] Move cust data note to top, near "External data source"
- [ ] Resize external data sources so they are the same size
- [ ] Inside External data source, switch SophieHub to unifiAccess
- [ ] Move LUIS next to Bot App, not above
- [ ] Check font of Azure Table Storage, make same size
- [ ] Note that Azure Table Storage will move to CosmosDB
- [ ] Change LUIS text to Language Understanding Service (aka LUIS)
- [ ] Encapsulate Bot App, Bot Service and Adaptive Card in box, Microsoft Bot Framework
- [ ] Add sophie site to diagram
- [ ] Correct bottom right text to "SSW SophieBot"
- [ ] Put URL underneath the text above
- [ ] In External data source, change "MS dyn365" to "CRM, e.g., dyn365, salesforce, etc"
