### ISSUE TITLE
📝 Encourage pinning of the bot

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#392]
Cc: @adamcogan 

Hi @DavidAbraham082 

### Pain

It's suggested for employees to pin SophieBot chat in their Teams app. 

### Tasks

- [x] 1. Read and then action # 2 on the [try out page](https://sswsophie.com/try/) about how to pin the bot
- [x] 2. Add a line of text in the "Hi" response card to indicate pinning the chat.
![image](https://user-images.githubusercontent.com/16027480/147453053-66a7b890-0012-4c12-91d0-fc534395600f.png)
**Figure: Add indicating text here**

### Screenshots

Thanks!

**Comment by DavidAbraham082** [comment]
Hey Jim,

To clarify:
> Add a line of text in the "Hi" response card to indicate pinning the chat.
Does this mean add a line of text to Sophie's response, which tells users to pin the chat?

Cheers

**Comment by DavidAbraham082** [comment]
> 2. Add a line of text in the "Hi" response card to indicate pinning the chat.    
**Done - published to Dev**

![image](https://user-images.githubusercontent.com/48205126/148140244-53aaeed7-d7a6-4c94-b854-d7b203f147ff.png)
**Figure: full text reads, "Tip: Pin this chat, so you can always find me!"**

**Comment by jimmidier** [comment]
- [ ] Pin message can go on bottom of card, with pin emoji
