### ISSUE TITLE
♻️ Update "Today" field on profile card

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#427]
Cc: @adamcogan @pierssinclairssw 

Hi @ravidhaduk 

### Pain

As per conversation during sprint review, we need the profile card to display a more detailed client information

### Screenshot 
![image](https://user-images.githubusercontent.com/80997507/160944957-b3ffa438-bcad-413e-a09a-2fe330b9d118.png)
Figure: Previous version of profile card.

### What code could be improved?

https://github.com/SSWConsulting/SSW.SophieBot/blob/main/bots/employee-finder/src/SSW.SophieBot/language-generation/en-us/profile.en-us.lg#L402

### Tasks

- [x] Investigate on fetching client ID
- [x] Update "Today" field to follow the format "Busy working for {client ID} - {client name} (Account Manager: {account manager full name})"

Thanks!

**Comment by jimmidier** [comment]
Done by updating People API to fetch client id and account manager name from CRM and integrate into SophieBot.

![image](https://user-images.githubusercontent.com/16027480/151336979-66c80478-3e19-46ac-85b0-ff88d39e4e0d.png)
**Figure: "Today" field now has the client id and the account manager name**

**Comment by jimmidier** [comment]
![image](https://user-images.githubusercontent.com/16027480/151500236-8410445e-8c95-456e-b051-fe1c7545d389.png)
**Figure: David's profile card doesn't have the client id and account manager name**
- [ ] Investigate
- [ ] Fix

**Comment by ravidhaduk** [comment]
As per the conversation in Sprint Review, we have to create Done Video for this PBI.
-[ ]  Create a Done Video.
