### ISSUE TITLE
✨Help Query - Add a see all questions button

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.SophieBot#429]
Cc: @adamcogan @ravidhaduk

Hi @jimmidier 
  
### Pain
When I am using SophieBot I want to be able to see all queries I can run from within SophieBot

### Suggested Solution
When I say "help" and SophieBot gives me a welcome message, it should have an option to see all questions.

### Tasks

- [ ] Implement "See all questions"

### More Information

N/A

### Screenshots
![image](https://user-images.githubusercontent.com/79821522/150258125-a1e4a5bd-0d6f-4341-84e8-2cc1ae038973.png)
**Figure: Add "See all questions" here**

Thanks!

**Comment by jimmidier** [comment]
Done by adding a button and a collapsible card.

![image](https://user-images.githubusercontent.com/16027480/151365701-2acd82fb-6dad-496b-a222-fa778443c892.png)
**Figure: "See all commands" button on the greeting card**
