### ISSUE TITLE
🐛 Data should be consistent for "When is Jake on client work"

### ISSUE THREAD

**Issue by ravidhaduk** [SSWConsulting/SSW.SophieBot#430]
Cc: @jimmidier 

### Describe the Bug

When asking "When is Jake on client work", SophieBot gives inconsistent data.

### To Reproduce
1. Go to 'Teams'
2. Type 'When is Jake on client work'
3. See inconsistent data.

### Expected Behavior

SophieBot should give the same data as the PowerBI reports indicate. 

### Tasks
- [x] Investigate
- [x] Fix

### Screenshots

![Screen Shot 2022-01-20 at 5 32 13 pm](https://user-images.githubusercontent.com/80997507/150286404-4ee29a39-a5bd-4132-9434-c1a94f30153a.png)
Figure: SophieBot returns a date 24th Jan.

![Screen Shot 2022-01-20 at 5 33 01 pm](https://user-images.githubusercontent.com/80997507/150286569-d6ec8142-3138-4d10-99ab-3fa205621d36.png)
Figure: PowerBI report shows Jake is booked today.

Thanks!

**Comment by jimmidier** [comment]
Fixed by separating next unavailability calculation from "next 4 weeks" and "starting today"

![image](https://user-images.githubusercontent.com/16027480/151361242-e3870e6c-67e3-4a8f-b95a-7e680bbe78ab.png)
**Figure: In this case we do a "next unavailability starting today"**
