### ISSUE TITLE
🐛"Who works on...?" Query

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.SophieBot#432]
Cc: @jimmidier, @pierssinclairssw, @PatrickZhao1989, @adamcogan 

Hi 
  
### Pain

This morning I tried to ask SophieBot who works on SSW.Rules.

 
![image](https://user-images.githubusercontent.com/19944129/150431046-7340d1c7-6b64-447e-9ea5-ad38b50df32d.png)

**Figure: Asking SophieBot who works on Rules**

As you can see form the screenshot, SophieBot could not answer.

### Suggested Solution

1.	Can you add this question:
“Who works on SSW.Rules?”
2.	The answer would be Jack, Tylah, Christian, Dale, Jake, Piers, and the link for more info.
3.	Data source would be this report https://app.powerbi.com/groups/456358f7-5b12-46f5-b952-2a37fa9bb5e8/reports/ccff2316-9422-467d-8025-d447097ba6de/ReportSection3 (filtered by This Quarter and the appropriate project).

![image](https://user-images.githubusercontent.com/19944129/150431091-068044ca-3ae1-42db-a088-3374bee2093d.png)
**Figure: PowerBI report of people working on SSW.Rules this quarter**

Thanks!

**Comment by jimmidier** [comment]
This has an existing intent, related PBI: #17  Label changed

**Comment by jimmidier** [comment]
Done by improving the LUIS model to recognize this expression. This is a recognizer bug for an existing command “Who is working on SSW.Rules”.

![image](https://user-images.githubusercontent.com/16027480/150905722-af92bae0-1e14-4090-a5ef-f8d56a0c7ec0.png)
**Figure: The bot is now able to answer this question**
