### ISSUE TITLE
🐛 Server error by incorrect spelling for query "who is in newcastle right now"

### ISSUE THREAD

**Issue by DavidAbraham082** [SSWConsulting/SSW.SophieBot#457]
CC: @adamcogan @jimmidier @PatrickZhao1989 @adamcogan 

Hi @pierssinclairssw 
  
### Pain

If I have a typo and my message fails to process correctly, I get a 500 message. This isn't very helpful

### Suggested Solution

A better error report, like, "I'm sorry, something went wrong. Please try that last message again"
If we're feeling really fancy, something like, "I didn't understand your last message. It looks like you meant, [closest similar message]"

### Tasks

- [x] improve error feedback

### Screenshots

![image](https://user-images.githubusercontent.com/48205126/151501580-6102870e-f007-428d-9b4c-fc237c9c6b8a.png)
**Figure: a 500 error message doesn't give me a lot of useful information**

Thanks!

**Comment by ravidhaduk** [comment]
As per my conversation with @pierssinclairssw, we want to display a generic error message to the user and log the Server error. So, we need to discuss it with Jim. I am putting this task on hold until that.
