### ISSUE TITLE
🐛  Showing incorrect skill level from CRM record

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.SophieBot#532]
CC: @jimmidier @ravidhaduk
### Describe the Bug
SophieBot showing incorrect skill level when you ask query related to skills. 

### Tasks
- [x] Investigate
- [x] Fix

### To Reproduce
1. Ask "Who knows Exploratory Testing?"
2. SophieBot correctly shows just one person, Lee Hawkins. Click on "Show All [1]"
3. You will skills level as "Intermediate".

### Expected Behavior
The skill level in this case should be "Advanced" as per Lee's CRM record.

### Screenshots
![image](https://user-images.githubusercontent.com/106290015/175187665-f8e6d0d8-a557-4a1f-9d96-1692eae59c77.png)
**Figure: Sophiebot responded my skills with Intermediate**

![image](https://user-images.githubusercontent.com/106290015/175187741-efbd65f0-e0b7-442a-8081-2fc3d29b679f.png)
**Figure: In CRM, my skills is set to Advanced level**
### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [x] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [x] Deployed to Dev
- [x] (If implemented) Pass automated UI testing
- [x] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [x] Complex code is documented (removing technical debt)
- [x] Deployed to Production
- [x] Add description about the changes for the PBI
- [x] Tick off the definition of done tasks in the PBI
- [x] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by ravidhaduk** [comment]
Done - Issue has been fixed now.

![image](https://user-images.githubusercontent.com/80997507/175885295-26358ccc-525b-4efd-9c97-8ed597766331.png)
**Figure: SophieBot reploed with correct skill Level**

![image](https://user-images.githubusercontent.com/80997507/175885385-64c2c7d4-d6a7-4aa1-a518-ca26ee0ef12d.png)
**Figure: SophieBot reply with correct skills level when you ask "Who knows react in sydney?"**

**Comment by leehawkinsssw** [comment]
Thanks, @ravidhaduk SophieBot now appears to report skill level correctly, both for me and others when I tried a number of different questions around skills.

Maybe this is a separate issue, but when I asked "Who knows critical thinking?", SophieBot responded with "Please specify a valid skill to query" but "Critical thinking" is a skill in CRM (and I have this skill on my user record).
