### ISSUE TITLE
🐛 Link to Internal Projects returns a 400

### ISSUE THREAD

**Issue by billyterblanche** [SSWConsulting/SSW.SophieBot#553]
Hi,

I was sitting here all alone in South Africa and I thought I would play with SophieBot a bit and ran into an issue when asking some of the questions as per [Module: Induction Part 5: Try out Sophie Bot queries](https://my.sugarlearning.com/SSW/items/13217/try-out-sophie-bot-queries).

### Describe the Bug
Link to [Internal Projects](https://prod-13.australiasoutheast.logic.azure.com/SitePages/Internal-Projects.aspx) provided by SophieBot when asking where certain resources are returns a 400 status code with response `{"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}}`

### To Reproduce
1. Go to SSW SophieBot in MS Teams
2. Ask:
   - Where is SugarLearning? or
   - Where is TimePro?
3. Wait for response to be returned
4. Click on [Internal Projects](https://prod-13.australiasoutheast.logic.azure.com/SitePages/Internal-Projects.aspx)
5. See error when browser tab is opened

See [Recording-SophiBot-Issue-2022-10-21-16-49-51](https://user-images.githubusercontent.com/10550900/197226588-b43b6789-8612-4b93-a9c8-2d21a5e29b57.gif)

### Expected Behavior
Site to load and not return a 400.

### Tasks
- [ ] Investigate
- [ ] Fix

### Environment
 - Device: [e.g. iPhone 12]
 - Browser: [e.g. chrome, safari]

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
This is due to old broken link in SophieBot's QnA knowledge base. Fixed now and closing the issue.
