### ISSUE TITLE
🐛 Who’s in Europe

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#555]
Cc: @JeanThirion @adamcogan 

Hi Team

### Describe the Bug

Feedback from @JeanThirion
> Investigate and fix the error I had searching for “Who’s in Europe” (see above)
       What happened?

### Tasks
- [x] Investigate
- [ ] Fix

### Screenshots

![image](https://user-images.githubusercontent.com/37203901/203210211-79c4b270-aa8f-42cd-aab7-94c616fde185.png)
**Figure: Got Error when asking Who’s in Europe**

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
This error is no longer occuring. Closing the issue now.
![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/16027480/62a5a99e-51d5-480b-885e-9deefec957e2)
