### ISSUE TITLE
🐛 Contractors do not appear in queries

### ISSUE THREAD

**Issue by chrisschultzssw** [SSWConsulting/SSW.SophieBot#560]
Hi SSW.SophieBot Devs

### Describe the Bug
Contractors do not appear in any query (e.g. who works in Sydney)

### To Reproduce
1. Go to SSW SophieBot
2. Ask "Who works in Sydney"
3. Contractors are missing, e.g. Will G

### Expected Behavior
Contractors should appear in queries

### Tasks
- [x] Investigate
- [ ] Fix

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
As Will G is now an ex employee I don't have the chance to reproduce the exact issue. I had a test on the other contractors and they do appear on the query result e.g. Lu Z and Gordon B. Closing the issue for now
