### ISSUE TITLE
🐛 SSW SophieBot not responding to chat messages.

### ISSUE THREAD

**Issue by n-crrn** [SSWConsulting/SSW.SophieBot#567]
Cc: @adamcogan, @pierssinclairssw 
Hi @jimmidier ,

### Describe the Bug
SSW SophieBot failed to respond to chat messages.

### To Reproduce
The steps to reproduce the behavior during the incident were:
1. Go to https://sswsophie.com/sophiebot/try/
2. Click on "Microsoft Teams" link near top of page.
3. Send chat message such as "Who works in Sydney office?"
4. Wait and observe that no response is received within one minute. After 10 minutes, there was still no response.

A possible contributing factor may have been that SSW SophieBot had not been accessed for an extended period of time.

### Expected Behavior
SSW SophieBot responds to messages within one minute under all circumstances.

### Tasks
- [x] Investigate
- [ ] Fix

### More Information
- FIrst attempt to contact SSW SophieBot failed at 3.43pm Tuesday 02 May 2023 AEST.
- Three independent users (all SSW employees Nick Curran, Matt Parker, and Piers Sinclair @pierssinclairssw) attempted to contact SSW SophieBot.
- Nothing seen until another attempt made to contact SSW SophieBot at 4.13pm Tuesday 02 May 2023 AEST. Screenshot attached.

### Environment
 - Microsoft Teams was being used through its web interface.
 - Device: Dell x86-based Laptop
 - Browser: Microsoft Edge Version 112.0.1722.64.
 - OS: Windows 11 OS Build 22621.1635

### Screenshots

![SophieBot Bug Delay and Recovery](https://user-images.githubusercontent.com/6274048/235593271-c5cf678b-5972-48f6-9adb-7e73136c8a7f.png)

**Figure: Screenshot is of the chat screen seen when attempting to contact SSW SophieBot.**

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

EDIT: Added timezone information.

**Comment by jimmidier** [comment]
Here's the monitoring info after over a month:

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/16027480/9ac71e33-8017-49d4-b67e-bdaa1f86af70)
**Figure: `HeartbeatSlow` events at the occurrence point**

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/16027480/ed841590-4877-42ed-a333-6728faf32705)
**Figure: No `HeartbeatSlow` events since the server scaling up**

Closing the issue.
