### ISSUE TITLE
🐛 Certain project queries are not working

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#570]
Cc: @Hona @william-liebenberg @jimmidier @pierssinclairssw @adamcogan

To myself,

### Describe the Bug

Feedback from @Hona as per email "SophieBot - Problems & Suggestions"
> Please investigate & raise as PBIs if you agree these should be functional
      > whos on clean architecture today
      > Who's working for Clean Architecture today?
      > Who's booked on Clean Architecture v2 project today?

The above project queries are not working.

### Tasks
- [x] Investigate
- [ ] Fix

### Screenshots

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/81e01f6e-6bbd-4623-aad8-32c32d693ec7)
**Figure: Failed project queries**

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
Considering the similarity between the query "Who's in Sydney" and "Who's in/on Clean Architecture", one safer way is to change the entity type of "Project" from "ML Entity" to "List Entity", just like it was done for the "site" entity. 

In order to do so, People API changes are involved.
