### ISSUE TITLE
🐛  SSW SophieBot fails to display bookings when requested

### ISSUE THREAD

**Issue by ncn-ssw** [SSWConsulting/SSW.SophieBot#585]
Cc: @adamcogan
Hi @jimmidier,

### Describe the Bug
SSW SophieBot fails to display any bookings when requested.

### To Reproduce
1. Send chat message "Show me {{ EMPLOYEE }} bookings" to SSW SophieBot.

Regardless of whose calendar is requested, SSW SophieBot responds consistently with "No calendar available".

<img src='https://github.com/SSWConsulting/SSW.SophieBot/assets/132531112/1e9ded01-fa93-4f63-b4d6-f93d6174ffb3' width='400'/>

**Figure: Screenshot of responses starting 3:47pm AEST on 13 June 2023**

<img src='https://github.com/SSWConsulting/SSW.SophieBot/assets/132531112/8ac46ecb-bc67-4f6a-8fa0-a5400136ca9d' width='400'/> 

**Figure: Screenshot of responses starting 4:12pm AEST on 13 June 2023**

### Expected Behavior
Bookings would be displayed as per the below figure.

<img src='https://github.com/SSWConsulting/SSW.SophieBot/assets/132531112/b8022dda-1683-4a60-8b90-5376d7e2c575' width='400'/> 

**Figure: The demonstration instruction on the [Try out the SSW SophieBot v2 page](https://sswsophie.com/sophiebot/try/)**

### Tasks
- [ ] Investigate
- [ ] Fix

### More Information
 - Behavior seen by Nick Curran and Brady Stroud @bradystroud
 - The command is supported according to the [Try out the SSW SophieBot v2 page](https://sswsophie.com/sophiebot/try/).

### Environment
 - Microsoft Teams Version 1.6.00.13566 (64-bit)
 - Device: Laptop x86-based Laptop
 - OS: 22621.1702

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
This has been fixed on People API. Now displaying Dynamics tracked calendar as below
![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/16027480/394e67d4-c0b8-434d-a8b5-08fb12de278b)
