### ISSUE TITLE
🐛 Who is in Strasbourg

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#599]
Cc: @jimmidier  @adamcogan 

To myself,

### Describe the Bug

There is no result when asking "who is in Strasbourg"

### Tasks
- [x] Investigate
- [x] Fix

### Screenshots

<img width="1001" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/acee3e9c-54f4-4dd3-9fd8-6ab13b668383">

**Figure: No results when asking Strasbourg**

### Acceptance Criteria

- [x] Meets [Definition of Done](../../_docs//Definition-of-Done.md)

Thanks!

**Comment by jimmidier** [comment]
This will be fixed once `Business Unit` or `Site` on CRM is properly updated, specifically on the address fields. Currently neither the `Europe` site nor `SSW France` business unit has any address info.

**Comment by AttackOnMorty** [comment]
Done - Added the detailed address info to the CRM

<img width="1013" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/1582b29e-9477-4b8a-bcb5-5fa8c2813d61">

**Figure: Response**
