### ISSUE TITLE
🐛 Booking status is not correct

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#602]
Cc: @jimmidier @william-liebenberg @adamcogan 

To myself

### Describe the Bug

Brady is booked today (Aug 24) but his booking status shows he is free.

### Tasks
- [ ] Investigate
- [ ] Fix

### Screenshots

<img width="992" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/dc4202d1-dd74-49b5-8e95-396a91e62b5f">

**Figure: Status is wrong**

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
Judging from CRM report Brady was not booked on Aug 24th
![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/16027480/575c5b23-93a8-45fa-ac44-8a139966756e)

**Comment by AttackOnMorty** [comment]
As per conversation with @jimmidier, the root cause is that the Appointments field returned by the PeopleAPI is empty. It also causes Bookings is always empty in the profile card.

Created a PBI in PeopleAPI to fix this: [Appointments field is empty](https://dev.azure.com/ssw/SSW.SophieBot/_sprints/backlog/SSW.SophieBot%20Team/SSW.SophieBot/PeopleBot%20-%20Sprint%203?workitem=83984)

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/1ef7f27d-0e44-43e4-b2d9-17bc376a33c2)
**Figure: Bookings are empty**

**Comment by AttackOnMorty** [comment]
Done - Fixed in [Appointments field is empty when fetching employees](https://dev.azure.com/ssw/SSW.SophieBot/_sprints/backlog/SSW.SophieBot%20Team/SSW.SophieBot/PeopleBot%20-%20Sprint%203?workitem=83984)
