### ISSUE TITLE
🐛 People number does not match for query - Who knows Azure

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#616]
Cc: @jimmidier @BrookJeynes @william-liebenberg @adamcogan 

To myself,

### Describe the Bug
There are 3 people on the selection card. But it shows 5 people after clicking.

### Tasks
- [ ] Investigate
- [ ] Fix

### More Information
![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/08bc089b-31db-4827-abfc-ec0e42a38523)

**Figure: Wrong number of people**

### Environment
 - Device: [e.g. iPhone 12]
 - Browser: [e.g. chrome, safari]

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
As per conversation with @AttackOnMorty, we're going to update PeopleAPI endpoint to add support for "site" query
