### ISSUE TITLE
🐛 Can't see who was in the Brisbane office

### ISSUE THREAD

**Issue by JackDevAU** [SSWConsulting/SSW.SophieBot#626]
Cc: @MattParkerDev @AttackOnMorty  

Hi SophieBot Team

### Describe the Bug

When I tried the following queries, I encountered an error

- Who has been in the brisbane office this past week?
- who has worked in the brisbane office this month?
- who has worked in the Brisbane office this week? 

### To Reproduce
1. Go to SophieBot
2. Enter the above queries
3. See error

### Expected Behavior

Show a list of who has been in the Brisbane office this past, week, month

### Tasks
- [x] Investigate
- [x] Fix

### Environment
 - Teams on Windows 11

### Screenshots

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/57518417/2998c6ec-60d4-47e5-b1f1-fb17002a0653)
Figure: Error messages

### Acceptance Criteria

- [x] Meets [Definition of Done](../../_docs//Definition-of-Done.md)

Thanks!

**Comment by AttackOnMorty** [comment]
Done - Fixed those queries

- Who has been in the brisbane office this past week?
- who has worked in the brisbane office this month?
- who has worked in the Brisbane office this week?

<img width="1001" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/b4f5a87c-6ba1-4ead-810e-e2e37ef33fc6">

<img width="985" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/23587756-3548-4372-884e-7268153e37be">


<img width="988" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/5a5a4a86-0ec9-474e-8903-c376fab9edf4">
