### ISSUE TITLE
🐛 Inactive skills appear on the profile card

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#659]
Based on email chain:

From: Daniel Mackay [SSW] <DanielMackay@ssw.com.au>
Date: Monday, November 13, 2023 at 16:42
To: Luke Mao [SSW] <LukeMao@ssw.com.au>
Cc: William Liebenberg [SSW] <WilliamLiebenberg@ssw.com.au>, Gordon Beeming [SSW] <GordonBeeming@ssw.com.au>, Adam Cogan [SSW] <AdamCogan@ssw.com.au>
Subject: SophieBot - Inactive Skills Showing

Cc: @jimmidier @GordonBeeming @william-liebenberg @pierssinclairssw @adamcogan 

To myslef

### Describe the Bug

Feedback from @danielmackay:
> (checked by Gordon)
> Hi Luke M,
> I have noticed that inactive skills are showing in SophieBot when you view someone’s skills.
> 1. Can you please update SophieBot so that inactive skills are not shown for a persons profile?
> ![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/3e2f6cc9-9a50-474e-a48e-92fe68b31bbd)
> **Figure: Inactive skills show on Daniel Mackay’s SophieBot profile**
> ![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/81d44ac1-9e90-49ec-950d-2e41dbe1f264)
> **Figure: Inactive Skills in CRM - [Skills Inactive Skills - Dynamics 365](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fssw.crm6.dynamics.com%2Fmain.aspx%3Fappid%3D05daa2a9-8768-446e-b9d3-580c8a6f9b8b%26forceUCI%3D1%26pagetype%3Dentitylist%26etn%3Dssw_skill%26viewid%3De11f017f-5685-4436-b85d-ddda8a007f27%26viewType%3D1039&data=05%7C01%7CLukeMao%40ssw.com.au%7Cd4fa7f13ddb04b7daeaf08dbe413bba1%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638354545635555622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MIs%2FZow7xIZa8xsY3E75s41UdwCLqsskTTm8x2FSeuo%3D&reserved=0)**
> ![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/5863c959-51fe-4ab8-91a9-203db81aa246)
> **Figure: Skill with a Status of Inactive - [Skill: SSW: zz.NET Core - Dynamics 365](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fssw.crm6.dynamics.com%2Fmain.aspx%3Fappid%3D05daa2a9-8768-446e-b9d3-580c8a6f9b8b%26forceUCI%3D1%26pagetype%3Dentityrecord%26etn%3Dssw_skill%26id%3D9445fed9-51b9-e811-814b-00155d01ef11&data=05%7C01%7CLukeMao%40ssw.com.au%7Cd4fa7f13ddb04b7daeaf08dbe413bba1%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638354545635555622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FWVipwD5WbGwvVqA%2FptvCUakBQnr7jnHzXRU3Q7c1ow%3D&reserved=0)**

### Tasks
- [x] Investigate
- [x] Fix

### Acceptance Criteria

- [x] Meets [Definition of Done](../../_docs//Definition-of-Done.md)
- [x] No inactive skills on the list

Thanks!

**Comment by AttackOnMorty** [comment]
✅ Done - PRs that fixed issue:
- https://dev.azure.com/ssw/SSW.SophieBot/_git/SSW.People.API/pullrequest/4793
- https://dev.azure.com/ssw/SSW.SophieBot/_git/SSW.People.API/pullrequest/4794

<img width="984" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/4eb94a4f-cf5b-4087-97d6-bff763c687d0">

**Figure: No inactive skills**

**Comment by danielmackay** [comment]
Have had a look at the PRs and the fix looks fine.
