### ISSUE TITLE
Make person name query exact match

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#70]
Related to #35 

Currently when querying using first name, the current People API uses fuzzy match. So when querying Lu, Luke will also be returned. We need exact matches on this.

![image](https://user-images.githubusercontent.com/16027480/132636040-22536bcd-e809-496a-8618-2f19966dc760.png)
**Figure: "Is Lu booked or free" query returns Lu and Luke's**

**Comment by AttackOnMorty** [comment]
This issue is no longer valid. We show a card to let the user choose a person.
